package ing.unibs.it;

public class Costanti {
	
	public static final String CODICE = "Codice univoco: ";
	public static final String ISCRIZIONE_OK = "Iscrizione rinnovata con successo!\n\n Prossima scadenza: %s \n\n Prossima data di rinnovo: %s \n";
	public static final String ISCRIZIONE_DECADUTA = "Iscrizione decaduta, ripeti l'iscrizione";
	public static final String ISCRIIONE_DOPO ="\n Al momento la tua iscrizione non può essere rinnovata, riprova il %s ma entro il %s \n";
	public static final String STAMPA_NOME= "\nNome: ";
	public static final String STAMPA_COGNOME="\nCognome: ";
	public static final String STAMPA_NASCITA = "\nData di nascita: " ;
	public static final String STAMPA_ISCRIIONE = "\nData di iscrizione: " ;
	public static final String STAMPA_RINNOVO = "\nRinnovo iscrizione : " ;
	public static final String STAMPA_SCADENZA = "\nData scadenza iscrizione: ";
	public static final String STAMPA_USER ="\n Username: ";
	public static final String ACCESSO_NEGATO ="\n Accesso riservato ai soli maggiorenni ";
	public static final String[] SCELTE_FRUITORE={"Iscriviti (Solo per Maggiorenni)","Accedi"};
	public static final String[] SCELTE_SOTTO_FRUITORE={"Rinnova Iscrizione", "riepilogo dati",};
	public static final String PASS_OPERATORE= "admin";
	public static final String TITOLO_PRINCIPALE="Benvenuto nel servizio di archiviazione e prestito di risorse multimediali ";
	public static final String[] SCELTE_PRINCIP= { "Sezione Utenti","Sezione Opertore"};
	public static final String TITOLO_OP="Cosa vuoi fare?";
	public static final String[] SCELTE_OP= { "Visualizza la lista dei fruitori attuali","Gestione libri"};
	public static final String INS_NOME="\n inserisci nome";
	public static final String INS_COGNOME="\n inserisci cognome";
	public static final String INS_NASCITA="\n inserisci la data di nascita";
	public static final String INS_CASA="\n inserissci luogo di Residenza";
	public static final String INS_USER="\n Inserisci username:";
	public static final String INS_PASS="\n Inserisci password";
	public static final String CREDENZIALI_NO="credenziali non vaide";
	public static final String COSA_="Cosa vuoi fare?";
	public static final String COM_NON_RIC="comando non riconosciuto";
	public static final String NESSUN_FRUIT="Nessun Fruitore registrato";
	public static final String PASS_ERRATA="Password errata";
	public static final String RIUSCITA="\nIscrizione Riuscita!";
	public static final String USER_NN_DISP="Username non disponibile";
	public static final String ACCESSO_OK="Accesso eseguito";	
	
	public static final String CATEGORIA_LIBRO="Categoria: Libro";
	public static final String SOTTOCAT="Sottocategoria: ";
	public static final String TITOLO="Titolo: ";
	public static final String NUM_PAG="Numero di pagine: ";
	public static final String ANNO_PUB="Anno di pubblicazione: ";
	public static final String CASA_ED="Casa editrice: ";
	public static final String NUM_LIC="Numero di Licenze: ";
	public static final String AUTORI= "Autori: ";
	public static final String LINGUA="Lingua: ";
	public static final String GENERE="Genere: ";
	public static final String INS_TITOLO="Insersci il titolo: ";
	public static final String INS_NPAGINE="Insersci il numero di pagine: ";
	public static final String INS_CASAED="Insersci la casa editrice: ";
	public static final String INS_GENERE="Insersci il genere: ";
	public static final String INS_ANNOPUBB="Insersci l'anno di pubblicazione: ";
	public static final String INS_NLIC="Insersci il numero di licenze: ";
	public static final String INS_LIBRO="In che categoria insersci il libro? ";
	public static final String[] SCELTE_SOTTOCAT={"libri in lingua inglese", "libri in lingua italiana",};
	public static final String REMOVE_LIBRO="Inserisci il titolo del libro da rimuovere: ";
	public static final String[] SCELTE_VISUALIZZ={"Visualizza libri in lingua inglese", "Visualizza libri in lingua italiana","Visualizza tutti i libri presenti"};
	public static final String[] SCELTE_SOTTO_LIBRI={"Aggiungi un libro ad una categoria", "rimuovi un libro dall'archivio","Visualizza i libri in archivio","Salva il lavoro"};
	public static final String MENU_LIBRI="Menu' libri: \n";
}
